version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "database/**",
  "storage/**",
  ".idea/**",
  "vendor/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/carboarded/Laravel-From-Scratch-Blog-Project"

[[transformers]]
name = "gofumpt"
enabled = true